services:
  user-postgres:
    container_name: USER_CONTAINER
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: user
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres-user:/var/lib/postgres/data
    networks:
      job-net:
    ports:
      - "9021:5432"
    restart: unless-stopped

networks:
  job-net:
    driver: bridge
volumes:
  postgres-user: